name: jjewellery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  meta: any
  dio: ^5.7.0
  mobile_scanner: ^6.0.2
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  shared_preferences: ^2.3.3
  intl: ^0.20.1
  sqflite: ^2.4.1
  uuid: ^4.5.1
  connectivity_plus: ^6.1.1
  fluttertoast: ^8.2.10
  syncfusion_flutter_charts: ^28.1.38
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  device_info_plus: ^11.2.2
  flutter_local_notifications: ^18.0.1
  syncfusion_flutter_datagrid: ^28.2.12
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/playstore.png
    - assets/images/nepali_flag.gif
    - assets/images/mtech_logo.jpg
    - assets/images/silver_img.png
    - assets/images/gold_img.png
    - assets/images/ktmSang.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300

    - family: Newa
      fonts:
        - asset: assets/fonts/Newa.ttf
